version: 0.2

phases:
  build:
    commands:
      - ./gradlew assembleRelease
      - ./gradlew generatePomFileForAarPublication
      - ./gradlew moveAAR
      - ./gradlew movePOM
artifacts:
  files:
    - uploadFolder/**/*