version: 0.2

phases:
  build:
    commands:
      - ./gradlew assembleRelease generatePomFileForAarPublication
artifacts:
  files:
    - liba/build/outputs/aar/liba-release.aar
  name: liba-renamed.aar