version: 0.2

phases:
  build:
    commands:
      - ./gradlew assembleRelease generatePomFileForAarPublication
artifacts:
  files:
    - app/build/outputs/apk/release/app-release-unsigned.apk
    - liba/build/outputs/aar/liba-release.aar
    - liba/build/publications/aar/pom-default.xml
    - libb/build/outputs/aar/libb-release.aar
    - libb/build/publications/aar/pom-default.xml
  discard-paths: yes