version: 0.2

phases:
  build:
    commands:
      - ./gradlew assembleRelease generatePomFileForAarPublication
artifacts:
  files:
    - liba/build/outputs/aar/liba-release.aar
  secondary-artifacts:
    artifact1:
      files:
        - liba/build/outputs/aar/liba-release.aar
      name: androidSDK/liba/0.0.1/liba-0.0.1.aar